//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.01 at 05:37:45 PM WEST 
//


package org.openxdm.xcap.client.appusage.omapresrules.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openxdm.xcap.client.appusage.omapresrules.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProvideRegistrationState_QNAME = new QName("urn:oma:xml:prs:pres-rules", "provide-registration-state");
    private final static QName _ProvideNetworkAvailability_QNAME = new QName("urn:oma:xml:prs:pres-rules", "provide-network-availability");
    private final static QName _ProvideWillingness_QNAME = new QName("urn:oma:xml:prs:pres-rules", "provide-willingness");
    private final static QName _ProvideBarringState_QNAME = new QName("urn:oma:xml:prs:pres-rules", "provide-barring-state");
    private final static QName _ProvideSessionParticipation_QNAME = new QName("urn:oma:xml:prs:pres-rules", "provide-session-participation");
    private final static QName _ServiceId_QNAME = new QName("urn:oma:xml:prs:pres-rules", "service-id");
    private final static QName _ProvideGeopriv_QNAME = new QName("urn:oma:xml:prs:pres-rules", "provide-geopriv");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openxdm.xcap.client.appusage.omapresrules.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "provide-registration-state")
    public JAXBElement<Boolean> createProvideRegistrationState(Boolean value) {
        return new JAXBElement<Boolean>(_ProvideRegistrationState_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "provide-network-availability")
    public JAXBElement<Boolean> createProvideNetworkAvailability(Boolean value) {
        return new JAXBElement<Boolean>(_ProvideNetworkAvailability_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "provide-willingness")
    public JAXBElement<Boolean> createProvideWillingness(Boolean value) {
        return new JAXBElement<Boolean>(_ProvideWillingness_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "provide-barring-state")
    public JAXBElement<Boolean> createProvideBarringState(Boolean value) {
        return new JAXBElement<Boolean>(_ProvideBarringState_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "provide-session-participation")
    public JAXBElement<Boolean> createProvideSessionParticipation(Boolean value) {
        return new JAXBElement<Boolean>(_ProvideSessionParticipation_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "service-id")
    public JAXBElement<String> createServiceId(String value) {
        return new JAXBElement<String>(_ServiceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:prs:pres-rules", name = "provide-geopriv")
    public JAXBElement<String> createProvideGeopriv(String value) {
        return new JAXBElement<String>(_ProvideGeopriv_QNAME, String.class, null, value);
    }

}
