//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.29 at 05:47:55 PM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.oma;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobicents.slee.sippresence.pojo.pidf.oma package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobicents.slee.sippresence.pojo.pidf.oma
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BarringState }
     * 
     */
    public BarringState createBarringState() {
        return new BarringState();
    }

    /**
     * Create an instance of {@link NetworkAvailability.Network }
     * 
     */
    public NetworkAvailability.Network createNetworkAvailabilityNetwork() {
        return new NetworkAvailability.Network();
    }

    /**
     * Create an instance of {@link OverridingWillingness }
     * 
     */
    public OverridingWillingness createOverridingWillingness() {
        return new OverridingWillingness();
    }

    /**
     * Create an instance of {@link Willingness }
     * 
     */
    public Willingness createWillingness() {
        return new Willingness();
    }

    /**
     * Create an instance of {@link RegistrationState }
     * 
     */
    public RegistrationState createRegistrationState() {
        return new RegistrationState();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link SessionParticipation }
     * 
     */
    public SessionParticipation createSessionParticipation() {
        return new SessionParticipation();
    }

    /**
     * Create an instance of {@link NetworkAvailability }
     * 
     */
    public NetworkAvailability createNetworkAvailability() {
        return new NetworkAvailability();
    }

    /**
     * Create an instance of {@link ServiceDescription }
     * 
     */
    public ServiceDescription createServiceDescription() {
        return new ServiceDescription();
    }

}
