//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.29 at 05:47:55 PM WET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oma:xml:prs:pidf:oma-pres", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mobicents.slee.sippresence.pojo.pidf.oma;
