//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.20 at 08:21:23 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:xcap-caps", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openxdm.xcap.client.appusage.xcapcaps;
