//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.05 at 12:23:31 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ietf:params:xml:ns:xcap-error", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openxdm.xcap.client.error;
