/*
 * CommListener.java
 *
 * Created on 18 de Novembro de 2002, 15:23
 */

package com.ptin.xmas.control.common.interfaces;
import javax.sip.message.Request;
import com.ptin.xmas.control.common.interfaces.*;
import javax.sip.header.CallIdHeader;
import javax.sip.SipProvider;
/**
 *  Interface used by ManagerImpl,implemented by CommProviderImpl and mainly used to register the application
 * 
 * @author  xest188
 */

public interface CommProvider {
    /**
     *The method used to set the ManagerListener(interface implemented by Manager)
     *
     */
    public void setManagerListener(CallManager managerListener_);
    /**
     *Method that removes the ManagerListener(interface implemented by Manager) represented 
     *by its name "app"
     */
    public void removeManagerListener(String app);
    /**
     *Method used to send a Request. Usualy a REGISTER Request.
     */
    public void sendRequest(Request request);
    /**
     *The method to stop the stack!
     */
    public void stop() throws Exception;
    /**
     *The method to start the stack!
     */
    public void start() throws Exception;
    /**
     *Function that returns the SipProvider from CommProviderImpl.
     */
    public SipProvider getSipProvider();
    /**
     *Function that returns the ManagerListener based on a given name "app"
     */
    public CallManager getManagerListener(String app);
    /**
     *Function that returns a new CallIdHeader generated by SipProvider.
     */
    public CallIdHeader getNewCallIdHeader();
}
