//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.02 at 04:49:42 PM WEST 
//


package org.mobicents.slee.sipevent.server.subscription.winfo.pojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobicents.slee.sippresence.pojo.winfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobicents.slee.sippresence.pojo.winfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Watcherinfo }
     * 
     */
    public Watcherinfo createWatcherinfo() {
        return new Watcherinfo();
    }

    /**
     * Create an instance of {@link Watcher }
     * 
     */
    public Watcher createWatcher() {
        return new Watcher();
    }

    /**
     * Create an instance of {@link WatcherList }
     * 
     */
    public WatcherList createWatcherList() {
        return new WatcherList();
    }

}
