package org.mobicents.media.msc.common.events;

public enum MsConnectionEventID {

	CONNECTION_CREATED, CONNECTION_MODIFIED, CONNECTION_DELETED, TX_FAILED, CONNECTION_CONNECTED, CONNECTION_FAILED, CONNECTION_DISCONNECTED;

}
